oauth2/README.md
oauth2/pom.xml
oauth2/src/main/java/fish/payara/security/annotations/OAuth2AuthenticationDefinition.java
oauth2/src/main/java/fish/payara/security/oauth2/OAuth2AuthenticationMechanism.java
oauth2/src/main/java/fish/payara/security/oauth2/OAuth2MechanismHandler.java
oauth2/src/main/java/fish/payara/security/oauth2/OAuth2StateHolder.java
oauth2/src/main/java/fish/payara/security/oauth2/api/OAuth2AccessToken.java
oauth2/src/main/java/fish/payara/security/oauth2/api/OAuth2State.java
oauth2/src/main/java/fish/payara/security/oauth2/api/OAuthIdentityStore.java
oauth2/src/main/java/fish/payara/security/oauth2/package-info.java
oauth2/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
pom.xml

OAuth2 Client - Security Connector maven coordinates:
groupId: **fish.payara.security.connectors**
artifactId: **security-connector-oauth2-client**
Moved from https://github.com/payara/Payara/tree/master/appserver/payara-appserver-modules/security-oauth2.

SEC-3 Security Connector - OAuth2 Client

---

oauth2/pom.xml
oauth2/src/main/java/fish/payara/security/oauth2/OAuth2AuthenticationMechanism.java
oauth2/src/main/java/fish/payara/security/oauth2/api/OAuthIdentityStore.java
oauth2/src/main/java/fish/payara/security/oauth2/package-info.java
openid/pom.xml
openid/src/main/java/fish/payara/security/annotations/AzureAuthenticationDefinition.java
openid/src/main/java/fish/payara/security/annotations/GoogleAuthenticationDefinition.java
openid/src/main/java/fish/payara/security/annotations/OpenIdAuthenticationDefinition.java
openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
openid/src/main/java/fish/payara/security/openid/OpenIdIdentityStore.java
openid/src/main/java/fish/payara/security/openid/controller/TokenController.java
pom.xml

Changes in this PR:
- Maven Release profile added including plugin (maven-javadoc-plugin, nexus-staging-maven-plugin, maven-gpg-plugin etc)
- Pom polished, distributionManagement, scm, license, developer, and other details added.
- Various Javadoc error fixed
- Version changed to 1.0

SEC-4 Release fish.payara.security.connectors 1.0

---

.project
.settings/org.eclipse.m2e.core.prefs
oauth2/.project
oauth2/.settings/org.eclipse.m2e.core.prefs
openid/.classpath
openid/.project
openid/.settings/org.eclipse.jdt.apt.core.prefs
openid/.settings/org.eclipse.jdt.core.prefs
openid/.settings/org.eclipse.m2e.core.prefs
openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
openid/src/main/java/fish/payara/security/openid/OpenIdCredential.java
openid/src/main/java/fish/payara/security/openid/api/OpenIdContext.java
openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java

This is a bug fix to validate access token expiry for every request and setting the correct expiry datatype.
https://github.com/payara/Payara/pull/4570
Manual tested with Google and Azure OIDC provider

ECOSYS-118 Validate AccessToken expiry on each request

---

oauth2/pom.xml
openid/pom.xml
pom.xml

Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>

FISH-254 Payara Security Connectors version increment 1.1.1-SNAPSHOT

---

pom.xml

This is required for Payara compatibility

Update Microprofile version to 4.0.1

---

oauth2/pom.xml
openid/src/main/java/fish/payara/security/openid/OpenIdUtil.java

Port of https://github.com/payara/Payara/pull/5212
Also removes the duplicate dependency in the Oauth2 pom.xml

FISH-84 Port a fix from main Payara repo

---

openid/src/main/java/fish/payara/security/openid/controller/StateController.java
security-connectors-api/src/main/java/fish/payara/security/openid/api/OpenIdConstant.java

Compared to Server's implementation, storing original request is considered
part of state that it stored at authentication start.

FISH-426: Port to security connectors repo

---

oauth2/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Updated patched project for FISH-5672 - updating Payara 6

Update version to 3.0.alpha2-SNAPSHOT

---

oauth2/pom.xml
openid-standalone/pom.xml
openid/pom.xml
openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
pom.xml
security-connectors-api/pom.xml

Release bunch of OpenId annotation improvements.

FISH-5852 Release Security Connector v2.2.0

---

.gitignore
openid/pom.xml
openid/src/main/java/fish/payara/security/openid/AzureDefinitionConverter.java
openid/src/main/java/fish/payara/security/openid/GoogleDefinitionConverter.java
openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationException.java
openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
openid/src/main/java/fish/payara/security/openid/OpenIdCredential.java
openid/src/main/java/fish/payara/security/openid/OpenIdUtil.java
openid/src/main/java/fish/payara/security/openid/controller/AuthenticationController.java
openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
openid/src/main/java/fish/payara/security/openid/controller/JWTValidator.java
openid/src/main/java/fish/payara/security/openid/controller/ProviderMetadataContoller.java
openid/src/main/java/fish/payara/security/openid/domain/AccessTokenImpl.java
openid/src/main/java/fish/payara/security/openid/domain/OpenIdConfiguration.java
openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java
openid/src/main/java/fish/payara/security/openid/domain/OpenIdProviderMetadata.java
openid/src/test/java/fish/payara/security/openid/domain/ConfigurationControllerTest.java
openid/src/test/java/fish/payara/security/openid/domain/OpenIdContextImplTest.java
pom.xml
security-connectors-api/src/main/java/fish/payara/security/annotations/AzureAuthenticationDefinition.java
security-connectors-api/src/main/java/fish/payara/security/annotations/GoogleAuthenticationDefinition.java
security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdAuthenticationDefinition.java
security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdProviderMetadata.java

Cherry-Picks all changes from the Security Connectors 2.2.0 release (FISH-5852) for the Payara 6 branch

FISH-5894 Sync Security Connectors 2.2.0 with Payara 6 branch

---

oauth2/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Tag created here: https://github.com/payara/ecosystem-security-connectors/tree/3.0.alpha2

Increment versions

---

oauth2/pom.xml
openid/pom.xml
pom.xml

Title.
Tracked down a failure in the DI TCK tracked back to these connectors and noticed this was still using MP 4.
Also adds Jakarta.* to osgi since it presumably needs it?

FISH-5982 FISH-6016 Update for MicroProfile 5

---

oauth2/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Tag created here: https://github.com/payara/ecosystem-security-connectors/tree/3.0.alpha3

FISH-6016 Alpha 3 Release

---

oauth2/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Version incremented to new SNAPSHOT

FISH-5941 new SNAPSHOT version

---

oauth2/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Tested with the Payara Samples and sample app to authenticate with Google OAuth client.

FISH-6431 Release Payara Security Connectors 3.0.alpha5

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Staging repo: https://oss.sonatype.org/content/repositories/fishpayara-2108

FISH-6480 Release security connectors 2.4.0

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
pom.xml
security-connectors-api/pom.xml

https://oss.sonatype.org/content/repositories/fishpayara-2110
Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>

FISH-6480 Release security connectors 3.0.Alpha6

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>

FISH-6480 Increment security connectors version to 3.0.alpha7-SNAPSHOT

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Updates the plugins to avoid CVE.

FISH-7820 FISH-7827 FISH-7828 FISH-7829 Update Nimbus-Jose-JWT, Accessors Smart, and Json Smart

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Tested Payara Micro with `GoogleAuthenticationDefinition`

FISH-8727 Release Security Connectors v3.1.1

---

openid/src/test/java/fish/payara/security/openid/controller/ConfigurationControllerTest.java

Adding two tests, which evaluate to comma -- this verifies, that our parsing doesn't parse real values by mistake.

FISH-8260 Add More Tests with Comma in the Value

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Release version numbers 4.0.0.Alpha1

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Increment version for Development iteration

Increment Version Numbers 4.0.0.Alpha2-SNAPSHOT

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Upgraded dependencies, fixed non-compiling tests and resolved OSGI error

FISH-10140 Fix failing tests and OSGI error

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Release version numbers 4.0.0.Alpha2

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Increment version for Development iteration

Increment Version Numbers 4.0.0.Alpha3-SNAPSHOT

---

.github/workflows/verify_pr.yml
Jenkinsfile
pom.xml

Upgrades dependency. Payara builds and passes all tests.

FISH-10576 Update JSON Smart (Payara7)

---

.github/workflows/verify_pr.yml
Jenkinsfile
pom.xml

Upgrades dependency. Payara builds and passes all tests.

FISH-10576 Update JSON Smart (Payara6)

---

.github/workflows/verify_pr.yml
Jenkinsfile
openid/pom.xml
pom.xml

Upgrades dependency. Payara builds and passes all tests.

FISH-10576 Update JSON Smart (Payara5)

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Release version numbers 2.8.1

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Release version numbers 3.1.2

---

oauth2/pom.xml
openid-standalone-it/pom.xml
openid-standalone/pom.xml
openid/pom.xml
pom.xml
security-connectors-api/pom.xml

Increment version for Development iteration

Increment Version Numbers 2.8.2-SNAPSHOT
