payara/ecosystem-security-connectors

- CHANGELOG.md
- openid-standalone/pom.xml
- openid/pom.xml
- openid/src/main/java/fish/payara/security/openid/AccessTokenCredential.java
- openid/src/main/java/fish/payara/security/openid/AccessTokenIdentityStore.java
- openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
- openid/src/main/java/fish/payara/security/openid/OpenIdCredential.java
- openid/src/main/java/fish/payara/security/openid/OpenIdIdentityStore.java
- openid/src/main/java/fish/payara/security/openid/api/AccessToken.java
- openid/src/main/java/fish/payara/security/openid/api/AccessTokenCallerPrincipal.java
- openid/src/main/java/fish/payara/security/openid/api/BearerGroupsIdentityStore.java
- openid/src/main/java/fish/payara/security/openid/api/Claims.java
- openid/src/main/java/fish/payara/security/openid/api/IdentityToken.java
- openid/src/main/java/fish/payara/security/openid/api/JwtClaims.java
- openid/src/main/java/fish/payara/security/openid/api/OpenIdClaims.java
- openid/src/main/java/fish/payara/security/openid/controller/TokenClaimsSetVerifier.java
- openid/src/main/java/fish/payara/security/openid/controller/TokenController.java
- openid/src/main/java/fish/payara/security/openid/domain/AccessTokenImpl.java
- openid/src/main/java/fish/payara/security/openid/domain/IdentityTokenImpl.java
- openid/src/main/java/fish/payara/security/openid/domain/JWTValidator.java
- openid/src/main/java/fish/payara/security/openid/domain/JsonClaims.java
- openid/src/main/java/fish/payara/security/openid/domain/NimbusJwtClaims.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdConfiguration.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java
- openid/src/test/java/fish/payara/security/openid/domain/NimbusJwtClaimsTest.java
- pom.xml
Bearer authentication expects JWT access token, that has been signed by the issuer. Token is validated for basic attributes (sub, iss, iat,nbf,  exp).
Application is expected to ship group providing IdentityStore, that read the access token from AccessTokenCallerPrincipal and decide caller's roles based on claims of the token (mostly audience and scope). There are too many application-specific options to put in an annotation.
Some of the things were refactored for better reuse and caching of remote resources (i. e. JWKS)
Other things were refactored to have more typesafe interface -- JwtClaims and OpenIdClaims are both read-only interfaces now, that return Optional values, as more often null than one would with (i. e. user that wouldn't allow access to personal information).
Tested in …
> FISH-384: Support for Resource Servers -- Bearer authentication for JWT access tokens

- openid/src/main/java/fish/payara/security/openid/AccessTokenCredential.java
- openid/src/main/java/fish/payara/security/openid/AccessTokenIdentityStore.java
- openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
- openid/src/main/java/fish/payara/security/openid/OpenIdCredential.java
- openid/src/main/java/fish/payara/security/openid/OpenIdIdentityStore.java
- openid/src/main/java/fish/payara/security/openid/OpenIdUtil.java
- openid/src/main/java/fish/payara/security/openid/api/AccessTokenCredential.java
- openid/src/main/java/fish/payara/security/openid/controller/AuthenticationController.java
- openid/src/main/java/fish/payara/security/openid/controller/CacheKey.java
- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- openid/src/main/java/fish/payara/security/openid/controller/JWTValidator.java
- openid/src/main/java/fish/payara/security/openid/controller/StateController.java
- openid/src/main/java/fish/payara/security/openid/controller/TokenController.java
- openid/src/main/java/fish/payara/security/openid/domain/AccessTokenImpl.java
- openid/src/main/java/fish/payara/security/openid/domain/IdentityTokenImpl.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdConfiguration.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java
The refactorings make `OpenIdConfiguration` injectable and remove it from method parameters and value objects, such as `AccessTokenCredential`.
This allows application to validate a token in obtains over other channels against current open id provider:
```
@Inject
IdentityStoreHandler identityStoreHandler;
@GET
@Path("authorize/{token}")
public Map<String, Object> decodeToken(@PathParam("token") String accessToken) {
var tokenCredential = new AccessTokenCredential(accessToken);
var validationResult = identityStoreHandler.validate(tokenCredential);
if (validationResult.getStatus() != CredentialValidationResult.Status.VALID) {
throw new ForbiddenException("Invalid token");
}
var principal = (AccessTokenCallerPrincipal) validationResult.getCallerPrincipal();
return …
```
> CLOUD-463: Allow programmiatic validation of JWT Access token

- pom.xml
Version 5 of the plugin changes the format and is incompatible, and requires more work to upgrade than just that of updating the version number in Payara.
> Set maven-bundle-plugin to 4.1.0 to match that of Payara server

- oauth2/pom.xml
- openid/pom.xml
After renaming the artifact, the dependent projects failed to build on a clean machine.
> FISH-786 Finish renaming security-api to security-connectors-api

- openid/src/main/java/fish/payara/security/openid/AccessTokenIdentityStore.java
- openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
- openid/src/main/java/fish/payara/security/openid/OpenIdExtension.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java
AccessTokenIdentityStore added to list of extension's beans.
Produced beans need explicit type IDs otherwise the runtime can consider
them the same.
Handle different validation statuses during bearer authentication.
Use Injection for OpenIdConfiguration rather than explicit setting.
> FISH-394: Fix support for Access Token authentication after changes

- openid/src/main/java/fish/payara/security/openid/AccessTokenIdentityStore.java
- openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
- openid/src/main/java/fish/payara/security/openid/OpenIdExtension.java
- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdAuthenticationDefinition.java
This is based on #82, merging that one will make the diff much slimmer, the implementation of the feature is actually just the last commit.
This is one of the possible implementations for supporting non-static (evaluated once per configuration) OpenIdConfigurationDefinition.
If MP Config property `payara.security.openid.sessionScopedConfiguration` is set to true, then OpenID connector is configured per session. That means that different users can authenticate using a different OIDC provider and configuration.
> FISH-385: Evaluate OpenId configuration per session

- openid/src/main/java/fish/payara/security/openid/OpenIdIdentityStore.java
When app with the standalone connector was redeployed, 
the connector classes in the new app clashed with the ones kept in 
the parent classloader:
```
Caused by: java.lang.IllegalAccessException: no such method: fish.payara.security.connectors.openid.OpenIdIdentityStore.validate(OpenIdCredential)CredentialValidationResult/invokeSpecial
at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:959)
at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
at java.base/java.lang.invoke.MethodHandles$Lookup.bind(MethodHandles.java:1694)
at javax.security.enterprise.identitystore.IdentityStore.validate(IdentityStore.java:84)
... 53 more
Caused by: …
```
> FISH-1370 Fix class leak when app is redeployed

- oauth2/pom.xml
- openid/pom.xml
Don't export MP packages. Allow to import MP Config 
from version 1.4 (MP 3.3) to 2.0+ (MP 4.0+)
This is needed to integrate to the latest Payara Enterprise.
> FISH-786: Support both MP 3.3. and 4.0+ in OSGi

- openid/src/main/java/fish/payara/security/openid/OpenIdIdentityStore.java
- openid/src/main/java/fish/payara/security/openid/domain/JsonClaims.java
Previously, it converted a group string into a string or strings that contain enclosing quotes in group name. This PR retrieves only the group names, without quotes in the string.
> FISH-1521: Fix for parsing groups from JWT token

- .gitignore
- openid/src/main/java/fish/payara/security/openid/AzureDefinitionConverter.java
- openid/src/main/java/fish/payara/security/openid/GoogleDefinitionConverter.java
- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdConfiguration.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/AzureAuthenticationDefinition.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/GoogleAuthenticationDefinition.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdAuthenticationDefinition.java
Adding support to get User Claims from ID Token
> FISH-5725: adding code to support get Claims from ID Token

- openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationException.java
- openid/src/main/java/fish/payara/security/openid/OpenIdUtil.java
- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- openid/src/main/java/fish/payara/security/openid/controller/JWTValidator.java
- openid/src/main/java/fish/payara/security/openid/controller/ProviderMetadataContoller.java
- openid/src/main/java/fish/payara/security/openid/domain/AccessTokenImpl.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdProviderMetadata.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdProviderMetadata.java
Enhance @OpenIdProviderMetadata with all necessary metadata to skip autoconfiguration as is currently supported by providerURI.
Reproducer is attached to the Jira issue FISH-5741.
Basically, the configuration can provide information this way:
```
@OpenIdAuthenticationDefinition(
//providerURI = "https://dev-ma-mtmzf.us.auth0.com",
providerMetadata = @OpenIdProviderMetadata(
issuer = "https://dev-ma-mtmzf.us.auth0.com/",
authorizationEndpoint = "https://dev-ma-mtmzf.us.auth0.com/authorize",
tokenEndpoint = "https://dev-ma-mtmzf.us.auth0.com/oauth/token",
userinfoEndpoint = "https://dev-ma-mtmzf.us.auth0.com/userinfo",
jwksURI = "https://dev-ma-mtmzf.us.auth0.com/.well-known/jwks.json",
responseTypesSupported = {"code", "token", "id_token", "code token", "code id_token",
"token id_token", …
```
> FISH-5743 FISH-5741 define oicd metadata locally

- openid/pom.xml
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java
- openid/src/test/java/fish/payara/security/openid/domain/OpenIdContextImplTest.java
this is the unit test related to the last changes to skip the userinfo endpoint with the new property userClaimsFromIDToken
> FISH-5725: unit test for new addition to skip userinfo endpoint

- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdProviderMetadata.java
Payara currently doesn't use subjectTypesSupported in OpenIdProviderMetadata plus there was its broken validation. This PR removes the validation completely and adds a comment, that the attribute is not used by the connector.
> Fish 5742 subject type supported metadata

- openid/src/main/java/fish/payara/security/openid/OpenIdUtil.java
Instead of reading string and parsing it, the new version uses String[] and follows the standard CDI way of parsing array from properties.
The only functional change is the delimiter in properties is comma ',' and not pipe '|'.
> FISH-5743 simplify code by using string array in call to config

- openid/src/main/java/fish/payara/security/openid/controller/AuthenticationController.java
- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdConfiguration.java
- openid/src/test/java/fish/payara/security/openid/domain/ConfigurationControllerTest.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdAuthenticationDefinition.java
Adding MicroProfile Config `payara.security.openid.extraParams.raw` to specify extraParams. It uses format of URL query (e.g. `payara.security.openid.extraParams.raw=a=x&c=y&c=some+other+spaces`) and allows also EL processing (needs to be explicitly mentioned in doc).
Annotation newly allows multiple keys.
Doc: https://github.com/payara/Payara-Community-Documentation/pull/271
> FISH-5745 load extra params from mp config, allow multiple keys

- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdConfiguration.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdAuthenticationDefinition.java
Adding new MP config property to relax scope validation
> Fish-386:relaxing validation for scopes security connector

- openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
- openid/src/main/java/fish/payara/security/openid/OpenIdCredential.java
- openid/src/main/java/fish/payara/security/openid/OpenIdUtil.java
- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- openid/src/test/java/fish/payara/security/openid/domain/ConfigurationControllerTest.java
Make the @OpenIdAuthenticationDefinition working also for Azure AD B2C, basically make parsing of expires_in more tolerant, expected number but provided a string.
Reproducing application is attached to the Jira ticket.
```
@OpenIdAuthenticationDefinition(
providerURI = "https://login.microsoftonline.com/${APP_ID}/",
providerMetadata = @OpenIdProviderMetadata(
// MS "supports" only openid, others fail validation
scopesSupported = {"email", "profile", "openid"}
),
clientId = "${CLIENT_ID}",
clientSecret = "{CLIENT_SECRET}",
redirectURI = "${baseURL}/callback",
logout = @LogoutDefinition(notifyProvider = true, redirectURI = "http://localhost:8080/OpenIdReproducer/"),
// long enough timeouts to be sure
jwksConnectTimeout = 2_000,
jwksReadTimeout = 2_000
)
```
Both Login and logout work well.
> Fish 383 working oauth for azure ad b2c

- openid/src/main/java/fish/payara/security/openid/AzureDefinitionConverter.java
- openid/src/main/java/fish/payara/security/openid/GoogleDefinitionConverter.java
- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdAuthenticationDefinition.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdProviderMetadata.java
Adding annotation property for OpenIdProviderMetadata to relax scope validation and be more consistent with implementation and complement the MP config that was already merged:
@AzureAuthenticationDefinition(clientId = "c6a4139e-eaac-4402-b72e-f52945882fc1", clientSecret = "WT37Q~xqXly0E69S~6xJm_B.AAbKM0~3SHOqu",
tenantId = "f1195e3a-584e-4eba-867f-030b6d4cffa9",
scope={"newScope"}, userClaimsFromIDToken = true, providerMetadata = @OpenIdProviderMetadata(
disableScopeValidation = true
))
I tested on local environment and both MP Config property and Annotation property work well
> FISH-386: adding annotation property to relax scope validation

- openid/pom.xml
Embed NimbusDs removed from pom.xml to avoid LinkageError in Payara Server.
> FISH-5941-embed-nimbusds-removed-from-pom

- openid-standalone/pom.xml
- openid/pom.xml
We don't want to interfere with server's classes and just not exporting them still causes
LinkageErrors when users' applications still use nimbus-jwt.
We let bundle plugin do the inclusion and then shade plugin to make relocation and
source jar
> FISH-5941: Relocate nimbus-jwt classes in openid connector

- openid/src/main/java/fish/payara/security/openid/OpenIdIdentityStore.java
- openid/src/main/java/fish/payara/security/openid/controller/AuthenticationController.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/ClaimsDefinition.java
I tried to use the openid-standalone module with JBoss but the redirection fails as I keep being redirected to /org.jboss.resteasy.specimpl.ResteasyUriBuilder@XXXX because redirection URIs are built using `UriBuilder.toString()` instead of `UriBuilder.build()`.
> redirect and logout URIs should be built using UriBuilder.build()

- .gitignore
- openid-standalone-it/pom.xml
- openid-standalone-it/src/main/java/fish/payara/security/openid/idp/AbstractIdProvider.java
- openid-standalone-it/src/main/java/fish/payara/security/openid/idp/AuthCode.java
- openid-standalone-it/src/main/java/fish/payara/security/openid/idp/NaiveCookieManager.java
- openid-standalone-it/src/main/java/fish/payara/security/openid/idp/Token.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/adfs/AccessTokenRoleMapping.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/adfs/AdfsAuth.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/adfs/AdfsEmulation.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/adfs/AdfsEmulationIT.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/adfs/JaxrsApplication.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/adfs/OpenIdCallback.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/adfs/UrlExtractor.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/idp/LogExceptionOnServerSide.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/idp/OpenIdDeployment.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/idp/simple/Callback.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/idp/simple/JaxrsApplication.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/idp/simple/SimpleIdProvider.java
- openid-standalone-it/src/test/java/fish/payara/security/openid/idp/simple/SimpleIdProviderIT.java
- openid/src/main/java/fish/payara/security/openid/AccessTokenIdentityStore.java
- openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- openid/src/main/java/fish/payara/security/openid/controller/TokenClaimsSetVerifier.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdConfiguration.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdProviderMetadata.java
- pom.xml
- security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdProviderMetadata.java
* added suite for testing OpenID features with Arquillian
* added test cases for ADFS behavior
* Fixed code paths, so that it is possible to include both IDP and client in single application
** Initialization of OpenId is postponed due to better heuristics of whether a request is an OAuth callback
> FISH-6434: Support for access token issuer different from ID token one

- openid/src/main/java/fish/payara/security/openid/AzureDefinitionConverter.java
- openid/src/main/java/fish/payara/security/openid/GoogleDefinitionConverter.java
- openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- openid/src/main/java/fish/payara/security/openid/domain/LogoutConfiguration.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdConfiguration.java
- openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java
- openid/src/main/java/fish/payara/security/openid/domain/ProxyConfiguration.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/AzureAuthenticationDefinition.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/GoogleAuthenticationDefinition.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdAuthenticationDefinition.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/ProxyDefinition.java
The PR aims to expand the functionality of the OIDC Connector by enabling proxy configuration. This addition is crucial for scenarios where the application interacts with an OpenID Connect provider through a reverse proxy, offering more flexibility in handling requests.
`@ProxyDefinition` serves as a means to specify details regarding proxy mapping within the OpenID Connect client configuration.
It contains attributes to specify the `hostName` and `port` of the proxied server.
Microprofile Config keys (`OPENID_MP_PROXY_HOSTNAME` and `OPENID_MP_PROXY_PORT`) have been added for the `hostname` and `port`, allowing configurable setup through properties.
Integration of proxy-related capabilities within the existing `@OpenIdAuthenticationDefinition`.
Includes a field `proxyDefinition()` within …
> FISH-8054 Proxy Support in OpenID Security Connector

- oauth2/pom.xml
- openid-standalone-it/pom.xml
- openid-standalone/pom.xml
- openid/pom.xml
- openid/src/main/java/fish/payara/security/openid/AzureDefinitionConverter.java
- openid/src/main/java/fish/payara/security/openid/GoogleDefinitionConverter.java
- openid/src/main/java/fish/payara/security/openid/OpenIdUtil.java
- openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
- openid/src/test/java/fish/payara/security/openid/controller/ConfigurationControllerTest.java
- openid/src/test/java/fish/payara/security/openid/domain/ConfigurationControllerTest.java
- pom.xml
- security-connectors-api/pom.xml
- security-connectors-api/src/main/java/fish/payara/security/annotations/AzureAuthenticationDefinition.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/GoogleAuthenticationDefinition.java
- security-connectors-api/src/main/java/fish/payara/security/annotations/OpenIdAuthenticationDefinition.java
Payara's OpenID annotations are now configurable in these ways:
```
extraParameters = {"a=1", "b=2", "c=3"}
extraParameters = {"a=#{1}", "b=#{2}", "c=#{3}"}
//securityBean.extraParametersArray returns array of strings in form of "a=1", "b=2", "c=3"
extraParametersExpression = "#{securityBean.extraParametersArray}"
//securityBean.extraParametersString returns string in format "a=1,b=2,c=3"
extraParametersExpression = "#{securityBean.extraParametersString}"
// MP Config value, overrides everything, backward compatibility, url syntax:
payara.security.openid.extraParams.raw=approval_prompt=force&access_type=offline&param_type=mp_override
```
> FISH-8260 Evaluate extraParams in OpenID
